[package]
name = "metar_decoder"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
jiff = { version = "0.2.15", features = ["serde", "logging"] }
nom = "8.0.0"
thiserror = "2.0.12"
